name: End-to-End Test
on: push
jobs:
  register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Cypress-run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test-Reigstration

  login-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Cypress-run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test-login

  excel-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Cypress-run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test-readExcel
          
  links-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Cypress-run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test-fetchalllinks
          